# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'VideoAudioCapture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'MJExtension'
	pod 'AFNetworking'
	pod 'SDWebImage'
  # Pods for VideoAudioCapture

end
